### ISSUE TITLE
Problem:  Need a feature file to describe antivirus testing

### ISSUE THREAD

**Issue by kellyannewithane** [artefactual-labs/archivematica-acceptance-tests#36] opened 2017-11-03 20:45 UTC
Feature file(s) needed to describe the virus testing that needs to be done for the following scenarios:

1) files < 20M that have virus
2) files < 20M that don’t have virus
3) files > 20 M that have virus
4) files > 20M that don’t have virus

And also for this issue:  https://github.com/JiscRDSS/rdss-archivematica/issues/104

Related: https://github.com/artefactual/archivematica/pull/772

**Comment by ross-spencer** [comment] 2017-11-08 04:59
Hi Kelly - Have started looking at this tonight. Should have something for you tomorrow at some point.

**Comment by ross-spencer** [comment] 2017-11-16 03:20
Okay, so I've been working away on this one since the sample files were submitted. The pain has just been losing time creating files and then scanning them. But we're almost there. 

Notes below:

@sevein and I have spoken via email and can confirm similar behaviour in (Ubuntu) Clamscan. Basically a limit at 2GB. Not 4GB as suggested in the manpage.

I have logged an issue with ClamAV here: https://bugzilla.clamav.net/show_bug.cgi?id=11958 

Copied here:

*Manpage suggests --max-filesize and --max-scansize can be set to just less than 4G. This output shows that the file is 'read' but the data scanned is zero for all files but the 2GB one:*

		ross-spencer@artefactual:~/git/go/src/github.com/ross-spencer/badfood:$ clamscan --max-filesize 4000M --max-scansize 4000M nukem/bigfile2000 
		nukem/bigfile2000: Win.Trojan.Nukem-1 FOUND

		----------- SCAN SUMMARY -----------
		Known viruses: 6342301
		Engine version: 0.99.2
		Scanned directories: 0
		Scanned files: 1
		Infected files: 1
		Data scanned: 1009.50 MB
		Data read: 2000.00 MB (ratio 0.50:1)
		Time: 481.938 sec (8 m 1 s)
		ross-spencer@artefactual:~/git/go/src/github.com/ross-spencer/badfood:$ clamscan --max-filesize 4000M --max-scansize 4000M nukem/bigfile2300
		nukem/bigfile2300: OK

		----------- SCAN SUMMARY -----------
		Known viruses: 6342301
		Engine version: 0.99.2
		Scanned directories: 0
		Scanned files: 1
		Infected files: 0
		Data scanned: 0.00 MB
		Data read: 2300.00 MB (ratio 0.00:1)
		Time: 25.129 sec (0 m 25 s)

		ross-spencer@artefactual:~/git/go/src/github.com/ross-spencer/badfood:$ clamscan --max-filesize 4000M --max-scansize 4000M nukem/bigfile4gb 
		nukem/bigfile4gb: OK

		----------- SCAN SUMMARY -----------
		Known viruses: 6342301
		Engine version: 0.99.2
		Scanned directories: 0
		Scanned files: 1
		Infected files: 0
		Data scanned: 0.00 MB
		Data read: 4100.00 MB (ratio 0.00:1)
		Time: 24.674 sec (0 m 24 s)

		ross-spencer@artefactual:~/git/go/src/github.com/ross-spencer/badfood:$ ls -la --block-size=M nukem/bigfile2000
		-rw-r--r-- 1 ross-spencer ross-spencer 2001M Nov 16 09:35 nukem/bigfile2000
		ross-spencer@artefactual:~/git/go/src/github.com/ross-spencer/badfood:$ ls -la --block-size=M nukem/bigfile2300
		-rw-r--r-- 1 ross-spencer ross-spencer 2301M Nov 16 09:29 nukem/bigfile2300
		ross-spencer@artefactual:~/git/go/src/github.com/ross-spencer/badfood:$ ls -la --block-size=M nukem/bigfile4gb 
		-rw-r--r-- 1 ross-spencer ross-spencer 4101M Nov 15 13:52 nukem/bigfile4gb

		ross-spencer@artefactual:~/git/go/src/github.com/ross-spencer/badfood:$ clamscan -V
		ClamAV 0.99.2/24047/Thu Nov 16 10:10:48 2017

		ross-spencer@artefactual:~/git/go/src/github.com/ross-spencer/badfood:$ lsb_release -a
		No LSB modules are available.
		Distributor ID:	Ubuntu
		Description:	Ubuntu 17.10
		Release:	17.10
		Codename:	artful

*--max-scansize seems to be the deciding factor.*

--

I have also attempted to find the issue in the code in the ClamAV development branch: https://github.com/vrtadmin/clamav-devel

I can't see anything too weird, but these lines:

* [Here the max-filesize default is set differently from the #define values](https://github.com/vrtadmin/clamav-devel/blob/a89cf90fdd59041969b50881a3dde14c514f636a/contrib/old-clamav-milter/clamav-milter.c#L2014) [#define value](https://github.com/vrtadmin/clamav-devel/blob/7a85da5c9ad54809218a7c797828e0f5abe26b0f/libclamav/default.h#L35)

* [Here they talk about a 2.17GB limit which does align with our values](https://github.com/vrtadmin/clamav-devel/blob/21b406f5f5755a470a39587591d29f072111c2fc/libclamav/scanners.c#L3812)

But my head isn't setup to debug this in more detail. 

Finally, references, for Clamscan:

* [Cryptshare go as far as saying Clamscan will only work with <=2GB files - so this is good to see](https://wiki.cryptshare.com/display/CSM/Pre-Processing)

* [Debian references a 2GB limit in their config options but this may just be a coincidence](https://wiki.cryptshare.com/display/CSM/Pre-Processing)

I will add some clamdscan notes below to confirm the behaviour there. 

*(Reminder: test - 4GB file with 2GB scan limit)  *

**NB.** Where I think this is going is that - here is some documentation for the future. For the feature file I'll drop the limits from 4GB to 2GB and note that we believe Clamscan (on some systems?) will only scan 2GB of data - anything bigger it won't scan at all. 

This sounds counter-intuitive for the integrity we're hoping for, but I will also document the rationale behind viruses being in small files for effectiveness not large files (inefficient). The feature file will also allow us to extend AV tools.

We might need to think about where in external documentation this information could go. @kellyannewithane did you have ideas about that?

**Comment by ross-spencer** [comment] 2017-11-16 22:28
We have an acknowledgement from the ClamAV team on Bugzilla: 

(Closed forum - sign up to see) https://bugzilla.clamav.net/show_bug.cgi?id=11958#c2

    Steven Morgan 2017-11-16 09:45:13 EST
   Thanks for your report. Targeting for 0.99.4

Current stable version 0.99.3

**Comment by ross-spencer** [comment] 2017-11-16 23:08
Clamdscan notes:

		ross-spencer@artefactual:~/git/go/src/github.com/ross-spencer/badfood:$ clamdscan -v nukem/bigfile2100 
		/home/ross-spencer/git/go/src/github.com/ross-spencer/badfood/nukem/bigfile2100: OK

		----------- SCAN SUMMARY -----------
		Infected files: 0
		Time: 0.001 sec (0 m 0 s)

		ross-spencer@artefactual:~/git/go/src/github.com/ross-spencer/badfood:$ clamdscan -v nukem/bigfile2000 
		/home/ross-spencer/git/go/src/github.com/ross-spencer/badfood/nukem/bigfile2000: Win.Trojan.Nukem-1 FOUND

		----------- SCAN SUMMARY -----------
		Infected files: 1
		Time: 435.080 sec (7 m 15 s)

		ross-spencer@artefactual:~/git/go/src/github.com/ross-spencer/badfood:$ ls -la --block-size=M nukem/bigfile2100
		-rw-r--r-- 1 ross-spencer ross-spencer 2101M Nov 16 09:34 nukem/bigfile2100

		ross-spencer@artefactual:~/git/go/src/github.com/ross-spencer/badfood:$ ls -la --block-size=M nukem/bigfile2000 
		-rw-r--r-- 1 ross-spencer ross-spencer 2001M Nov 16 09:35 nukem/bigfile2000

		ross-spencer@artefactual:~/git/go/src/github.com/ross-spencer/badfood:$ clamdscan -V
		ClamAV 0.99.2/24047/Thu Nov 16 10:10:48 2017

(Same issue)

**Comment by ross-spencer** [comment] 2019-09-11 19:57
Closing as this is largely resolved by: 

* [Black-box virus tests that mimic our regression tests](https://github.com/artefactual-labs/archivematica-acceptance-tests/pull/147). 
* [Documentation describing various antivirus scenarios](https://www.archivematica.org/en/docs/archivematica-1.10/user-manual/transfer/scan-for-viruses/ ).

Should a greater range of tests be required, then the sample data used in the black-box scenarios can be expanded upon, where thresholds need to be tested further. 

The range of files used in that scenario is as follows:
```bash
├── [-rw-r--r-- ross-spencer  731]  README.md
├── [-rw-r--r-- ross-spencer 1.0M]  test.1M.eicar.with-virus
├── [-rw-r--r-- ross-spencer 1.0M]  test.1M.nukem.with-virus
├── [-rw-r--r-- ross-spencer 1.0M]  test.1M.null.no-virus
├── [-rw-r--r-- ross-spencer  30M]  test.30M.eicar.with-virus
├── [-rw-r--r-- ross-spencer  30M]  test.30M.nukem.with-virus
├── [-rw-r--r-- ross-spencer  30M]  test.30M.null.no-virus
├── [-rw-r--r-- ross-spencer    0]  test.zero.byte.no-virus
└── [-rw-r--r-- ross-spencer  184]  test.zip.eicar.with-virus.zip
```

**Closed by ross-spencer** 2019-09-11 19:57 UTC
